# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f_rayleigh <- function(x, sigma) {
    .Call(`_packageC_f_rayleigh`, x, sigma)
}

