# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Maximo Divisor Comum
#'
#' @param a Um valor (int)
#' @param b Umm valor (int)
#' @return O MDC entre `a` e `b`
#' @useDynLib packageC, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @export
boost_mdc <- function(a, b) {
    .Call(`_packageC_boost_mdc`, a, b)
}

#' Maximo Divisor Comum
#'
#' @param a Um valor (int)
#' @param b Umm valor (int)
#' @return O MDC entre `a` e `b`
#' @useDynLib packageC, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @export
rcpp_mdc <- function(a, b) {
    .Call(`_packageC_rcpp_mdc`, a, b)
}

#' @title Generate Random Wishart Distribution
#' @description Creates a random wishart distribution when given degrees of freedom and a sigma matrix.
#' @param df An \code{int}, which gives the degrees of freedom of the Wishart (df > 0).
#' @param S An \code{matrix} with dimensions m x m that provides Sigma, the covariance matrix.
#' @return A \code{matrix} that is a Wishart distribution, aka the sample covariance matrix of a Multivariate Normal Distribution.
#' @seealso \code{\link{riwishart}}
#' @useDynLib packageC, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @export
rwishart <- function(df, S) {
    .Call(`_packageC_rwishart`, df, S)
}

#' @title Generate Random Inverse Wishart Distribution
#' @description Creates a random inverse wishart distribution when given degrees of freedom and a sigma matrix.
#' @param df An \code{int} that represents the degrees of freedom (df > 0).
#' @param S A \code{matrix} with dimensions m x m that provides Sigma, the covariance matrix.
#' @return A \code{matrix} that is an inverse wishart distribution.
#' @seealso \code{\link{rwishart}}
#' @useDynLib packageC, .registration = TRUE
#' @importFrom Rcpp evalCpp
#' @export
riwishart <- function(df, S) {
    .Call(`_packageC_riwishart`, df, S)
}

f_rayleigh <- function(x, sigma) {
    .Call(`_packageC_f_rayleigh`, x, sigma)
}

